CREATE TABLE IF NOT EXISTS PERSON(
 pid serial PRIMARY KEY,
 pass VARCHAR(255) NOT NULL,
 first_name VARCHAR(255) NOT NULL,
 second_name VARCHAR(255) NOT NULL,
 phone INTEGER,
 mail VARCHAR(255),
 score float default 0
);
CREATE TABLE IF NOT EXISTS TEAM(
 t_id serial PRIMARY KEY,
 leader_id INTEGER REFERENCES PERSON (pid),
 pr_id INTEGER REFERENCES PROJECT (pr_id),
 team_name VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS TEAM_WITH_MEMBERS(
 pid INTEGER REFERENCES PERSON (pid),
 t_id INTEGER REFERENCES TEAM (t_id),
 team_name VARCHAR(255) NOT NULL,
 score FLOAT DEFAULT 0,
 comments VARCHAR(255),
 order_no INTEGER
);
CREATE TABLE IF NOT EXISTS PROJECT(
 pr_id SERIAL PRIMARY KEY,
 manager_id INTEGER REFERENCES PERSON (pid),
 t_id INTEGER REFERENCES TEAM (t_id),
 pr_name VARCHAR(255) NOT NULL,
 is_active BOOL
);
CREATE TABLE IF NOT EXISTS ORGANIZATION(
 pid INTEGER REFERENCES PERSON (pid),
 pr_id INTEGER REFERENCES PROJECT (pr_id),
 t_id INTEGER REFERENCES TEAM (t_id)
);